services:
  caddy:
    image: ghcr.io/serfriz/caddy-cloudflare:2.11.4
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true

volumes:
  caddy_data:
  caddy_config:
