services:
  hass:
    image: ghcr.io/home-assistant/home-assistant:2026.6.4
    container_name: hass
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - ./config:/config
    mem_limit: 1700m
