services:
  wyoming-whisper:
    image: rhasspy/wyoming-whisper:3.3.1
    container_name: wyoming-whisper
    command: --model small-int8 --language fi
    volumes:
      - ./whisper-data:/data
    ports:
      - "10300:10300"
    restart: unless-stopped
